version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: rag_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.3.0
    container_name: rag_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  mongodb_data:
  qdrant_storage: